FROM plus3it/tardigrade-ci:0.21.6

COPY ./tests/requirements_test.txt /tests/requirements_test.txt
COPY ./requirements_common.txt /requirements_common.txt

RUN python -m pip install --no-cache-dir -r /tests/requirements_test.txt
