FROM plus3it/tardigrade-ci:0.24.0

USER root

#Set of all dependencies needed for pyenv to work on Ubuntu
RUN apt-get update \
        && apt-get install -y --no-install-recommends make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget ca-certificates curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev mecab-ipadic-utf8 git

USER tardigrade-ci

# Set-up necessary Env vars for PyEnv
ENV PYTHON_VERSION 3.8.10
ENV PYENV_ROOT /home/tardigrade-ci/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

# Install pyenv
RUN curl https://pyenv.run | bash \
    && pyenv update \
    && pyenv install $PYTHON_VERSION \
    && pyenv rehash \
    && pyenv global system ${PYTHON_VERSION}

COPY ./requirements/requirements_test.txt /app/requirements_test.txt
COPY ./requirements/requirements_common.txt /app/requirements_common.txt

RUN python -m pip install --no-cache-dir -r /app/requirements_test.txt
