name: Run test jobs
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: plus3it/actions-workflows/.github/workflows/test.yml@0a03f75193a010b3532cc90e8ad0b15a09ed33c1

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Run python lambda unit tests
        run: make docker/run target=pytest/lambda/tests
